stages:
  - build
  - test

variables:
  npm_config_cache: "/builds/santiago105/lumina-testing/.npm"
  CYPRESS_CACHE_FOLDER: "/builds/santiago105/lumina-testing/cache/Cypress"
  SLACK_WEBHOOK: "https://hooks.slack.com/services/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"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - "/builds/santiago105/lumina-testing/.npm"
    - "/builds/santiago105/lumina-testing/cache/Cypress"
    - "/builds/santiago105/lumina-testing/node_modules"

install:
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: build

  script:
    - if [ ! -d "$npm_config_cache" ]; then echo "Cache not restored, creating necessary directories"; mkdir "$npm_config_cache"; fi
    - mkdir -p $(dirname "$CYPRESS_CACHE_FOLDER")
    - if [ ! -d "$CYPRESS_CACHE_FOLDER" ]; then mkdir "$CYPRESS_CACHE_FOLDER"; fi
    - apt-get update
    - apt-get install -y default-jdk
    - export JAVA_HOME=$(update-java-alternatives -l | awk '{print $3}')
    - npx cypress cache path
    - npx cypress cache list
    - npx cypress info
    - npx cypress verify
    - npm i cypress-mochawesome-reporter

run_tests:
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: test
  script:
    - npm ci
    - apt-get update
    - apt-get install -y default-jdk
    - export JAVA_HOME=$(update-java-alternatives -l | awk '{print $3}')
    - npm i cypress-mochawesome-reporter
    - npx cypress run
  after_script:
   - report_link="$CI_PROJECT_URL/-/jobs/${CI_PROJECT_ID}/artifacts/browse/mochawesome-report"
   - echo ${report_link}
   - echo "Sending Slack Message with report link"
   - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Report is ready! Check it out: $report_link\"}' https://hooks.slack.com/services/T5J570KKL/B04LKMNPQL8/"
  artifacts:
    paths:
       - cypress/mochawesome-report
    expire_in: 1 day