stages:
  - build
  - test

variables:
  npm_config_cache: "/builds/santiago105/lumina-testing/.npm"
  CYPRESS_CACHE_FOLDER: "/builds/santiago105/lumina-testing/cache/Cypress"
  SLACK_WEBHOOK: "https://hooks.slack.com/services/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"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - "/builds/santiago105/lumina-testing/.npm"
    - "/builds/santiago105/lumina-testing/cache/Cypress"
    - "/builds/santiago105/lumina-testing/node_modules"

install:
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: build

  script:
    # check if cache has been restored
    - if [ ! -d "$npm_config_cache" ]; then echo "Cache not restored, creating necessary directories"; mkdir "$npm_config_cache"; fi
    - mkdir -p $(dirname "$CYPRESS_CACHE_FOLDER")
    - if [ ! -d "$CYPRESS_CACHE_FOLDER" ]; then mkdir "$CYPRESS_CACHE_FOLDER"; fi
    # check Cypress binary path and cached versions
    - apt-get update
    - apt-get install -y default-jdk
    - export JAVA_HOME=$(update-java-alternatives -l | awk '{print $3}')
    - echo JAVA_HOME
    - npx cypress cache path
    - npx cypress cache list
    - npx cypress info
    - npx cypress verify
    - npm install -g allure-commandline
    - npm i cypress-mochawesome-reporter

run_tests:
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: test
  script:
    - npm ci
    - npm install -g allure-commandline
    - npm i cypress-mochawesome-reporter
    - rm -r allure-results/ allure-report cypress/screenshots || true
        # Run cypress tests
    - npx cypress run --reporter cypress-mochawesome-reporter
    - npx allure generate allure-results --clean -o allure-report
  after_script:
  - echo "Sending Slack Message with report link"
  - report_link="$CI_PROJECT_URL/jobs/${CI_PROJECT_ID}/artifacts/allure-report"
  - echo report_link
  - if [ -d "allure-report" ]; then echo "allure-report exists"; else echo "allure-report does not exist"; fi
  - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Allure report is ready! Check it out: $report_link\"}' https://hooks.slack.com/services/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"
  - mv -f allure-report/history allure-results/history && rm -r allure-report || true
  artifacts:
    paths:
      - allure-report
      - mochawesome-report
      - allure-results/history
      - cypress/videos
      - cypress/screenshots
    expire_in: 1 day
