stages:
  - build
  - test

variables:
  npm_config_cache: "/builds/santiago105/lumina-testing/.npm"
  CYPRESS_CACHE_FOLDER: "/builds/santiago105/lumina-testing/cache/Cypress"
  SLACK_WEBHOOK: "https://hooks.slack.com/services/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"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

install:
  image: cypress/base:latest
  stage: build

  script:
    # create necessary folders if they don't exist
    - if [ ! -d "$npm_config_cache" ]; then mkdir "$npm_config_cache"; fi
    - if [ ! -d "$CYPRESS_CACHE_FOLDER" ]; then mkdir "$CYPRESS_CACHE_FOLDER"; fi
    # check Cypress binary path and cached versions
    - apt-get update
    - apt-get install -y default-jdk
    - export JAVA_HOME=$(/usr/libexec/java_home)
    - echo "JAVA_HOME=$JAVA_HOME"
    - npx cypress cache path
    - npx cypress cache list
    - $(npm bin)/print-env CI
    - npm run cy:verify
    - npm run cy:info
    - npx cypress verify
    - npx cypress run --record --key ${CYPRESS_RECORD_KEY}

run_tests:
  image: cypress/base:6.2.0
  stage: test
  script:
    - apt-get update
    - apt-get install -y openjdk-11-jdk
    - apt-get install -y chromium-chromedriver
    - chromedriver
    - npm ci
    - export JAVA_HOME=$(/usr/libexec/java_home)
    - echo $JAVA_HOME
    - java -version
    - /usr/libexec/java_home
    - $(npm bin)/print-env CI
    - npx cypress run --config baseUrl=${BASE_URL}
    - npx allure generate allure-results/
  after_script:
  - echo "Sending Slack Message with report link"
  - report_link="https://your-gitlab-domain.com$CI_JOB_URL/artifacts/allure-report"
  - echo report_link
  - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Allure report is ready! Check it out: $report_link\"}' https://hooks.slack.com/services/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"
  artifacts:
    paths:
      - allure-report
      - allure-results/history
      - cypress/videos
      - cypress/screenshots
    expire_in: 1 day