# first, install Cypress, then run all tests
stages:
  - build
  - test
  - pages

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
  SLACK_WEBHOOK: "https://hooks.slack.com/services/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"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

# this job installs NPM dependencies and Cypress
install:
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: build
  script:
    - npm ci
    # check Cypress binary path and cached versions
    # useful to make sure we are not carrying around old versions
    - npx cypress cache path
    - npx cypress cache list
    - npm run cy:verify
    - npm run cy:info

test:
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: test
  script:
    # Run cypress tests
    - npx cypress run --reporter mochawesome  --reporter-options reportDir=mochawesome-report,overwrite=false,html=false,json=true
  artifacts:
    expire_in: 30 days
    when: always
    paths:
      - mochawesome-report
      - cypress/screenshots

pages:
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: pages
  script:
    # move screenshots folder to public
    - mv cypress/screenshots public
    # Merge Json files
    - npx mochawesome-merge mochawesome-report/*.json -o merged.json
        # Generate the report using the merged JSON files as input.
    - npx mochawesome-report-generator merged.json
    # move mochawesome-report folder to public
    - mv mochawesome-report public
    - report_link="https://santiago105.gitlab.io/-/lumina-testing/-/jobs/$CI_JOB_ID/artifacts/public/merged.html"
    - echo "${report_link}"
    - slack_message="Report is ready! Check it out:"
    - 'curl -X POST -H "Content-type: application/json" --data "{\"text\":\"${slack_message}${report_link}\"}" https://hooks.slack.com/services/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'
  when: always
  only:
    - main
  artifacts:
    expire_in: 30 days
    when: always
    paths:
      - public
      - mochawesome-report
      - cypress/screenshots