stages:          # List of stages for jobs, and their order of execution
  - test


build-job:       # This job runs in the build stage, which runs first.
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: test
  script:
    - npm ci
    - npm run cypress:execution