stages:
  - build
  - test

variables:
  npm_config_cache: "/builds/santiago105/lumina-testing/.npm"
  CYPRESS_CACHE_FOLDER: "/builds/santiago105/lumina-testing/cache/Cypress"
  SLACK_WEBHOOK: "https://hooks.slack.com/services/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"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

install:
  image: cypress/base:latest
  stage: build

  script:
    # create necessary folders if they don't exist
    - if [ ! -d "$npm_config_cache" ]; then mkdir "$npm_config_cache"; fi
    - if [ ! -d "$CYPRESS_CACHE_FOLDER" ]; then mkdir "$CYPRESS_CACHE_FOLDER"; fi
    # check Cypress binary path and cached versions
    - apt-get update
    - apt-get install -y default-jdk
    - export JAVA_HOME=$(/usr/libexec/java_home)
    - echo "JAVA_HOME=$JAVA_HOME"
    - npx cypress cache path
    - npx cypress cache list
    - $(npm bin)/print-env CI
    - npx cypress info
    - npx cypress verify
    - npm install -g allure-commandline
    - npm i cypress-mochawesome-reporter

run_tests:
  image: cypress/base:latest
  stage: test
  script:
    - apt-get update
    - apt-get install -y openjdk-11-jdk
    - npm ci
    - export JAVA_HOME=$(/usr/libexec/java_home)
    - echo $JAVA_HOME
    - java -version
    - /usr/libexec/java_home
    - $(npm bin)/print-env CI
    - rm -r allure-results/ allure-report cypress/screenshots || true
        # Run cypress tests
    - npx cypress run --reporter mochawesome  --reporter-options reportDir=mochawesome-report,overwrite=false,html=false,json=true
    - npx allure generate allure-results --clean -o allure-report
  after_script:
  - echo "Sending Slack Message with report link"
  - report_link="https://gitlab.com$CI_PROJECT_URL/jobs/${CI_PROJECT_ID}/artifacts/allure-report"
  - echo $report_link
  - if [ -d "allure-report" ]; then echo "allure-report exists"; else echo "allure-report does not exist"; fi
  - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Allure report is ready! Check it out: https://gitlab.com$CI_PROJECT_URL/jobs/${CI_PROJECT_ID}/artifacts/allure-report\"}' https://hooks.slack.com/services/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"
  - echo $?
  - mv -f allure-report/history allure-results/history && rm -r allure-report || true
  artifacts:
    paths:
      - allure-report
      - mochawesome-report
      - allure-results/history
      - cypress/videos
      - cypress/screenshots
    expire_in: 1 day